name: Rust backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ./backend
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./backend
    - name: Run lint
      run: rustup component add clippy && cargo clippy
      working-directory: ./backend
    - name: Run Format
      run: rustup component add rustfmt && cargo fmt --all --manifest-path ./Cargo.toml -- --check
      working-directory: ./backend
